package solly.tutorials.calculator.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCalculator = createDescriptorForCalculator();
  /*package*/ final ConceptDescriptor myConceptInputField = createDescriptorForInputField();
  /*package*/ final ConceptDescriptor myConceptInputFieldReference = createDescriptorForInputFieldReference();
  /*package*/ final ConceptDescriptor myConceptOutputField = createDescriptorForOutputField();
  private final LanguageConceptSwitch myConceptIndex;

  public StructureAspectDescriptor() {
    myConceptIndex = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCalculator, myConceptInputField, myConceptInputFieldReference, myConceptOutputField);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myConceptIndex.index(id)) {
      case LanguageConceptSwitch.Calculator:
        return myConceptCalculator;
      case LanguageConceptSwitch.InputField:
        return myConceptInputField;
      case LanguageConceptSwitch.InputFieldReference:
        return myConceptInputFieldReference;
      case LanguageConceptSwitch.OutputField:
        return myConceptOutputField;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myConceptIndex.index(c);
  }

  private static ConceptDescriptor createDescriptorForCalculator() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("solly.tutorials.calculator", "Calculator", 0xb82c1489ef4142a8L, 0xa822be676a783f97L, 0x6edbdfc7873b5b41L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x33d23ee961a0cbf3L);
    b.origin("r:541fa709-e489-498e-8c7b-45b0d1ff3578(solly.tutorials.calculator.structure)/7988224412132006721");
    b.aggregate("inputFields", 0x6edbdfc7873bfb8dL).target(0xb82c1489ef4142a8L, 0xa822be676a783f97L, 0x6edbdfc7873bfb78L).optional(true).ordered(true).multiple(true).origin("7988224412132047757").done();
    b.aggregate("outputFields", 0x6edbdfc7873c25b2L).target(0xb82c1489ef4142a8L, 0xa822be676a783f97L, 0x6edbdfc7873c259dL).optional(true).ordered(true).multiple(true).origin("7988224412132058546").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("solly.tutorials.calculator", "InputField", 0xb82c1489ef4142a8L, 0xa822be676a783f97L, 0x6edbdfc7873bfb78L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:541fa709-e489-498e-8c7b-45b0d1ff3578(solly.tutorials.calculator.structure)/7988224412132047736");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputFieldReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("solly.tutorials.calculator", "InputFieldReference", 0xb82c1489ef4142a8L, 0xa822be676a783f97L, 0x6edbdfc7873c90bfL);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.baseLanguage.structure.Expression", 0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.origin("r:541fa709-e489-498e-8c7b-45b0d1ff3578(solly.tutorials.calculator.structure)/7988224412132085951");
    b.associate("field", 0x6edbdfc7873c90c0L).target(0xb82c1489ef4142a8L, 0xa822be676a783f97L, 0x6edbdfc7873bfb78L).optional(false).origin("7988224412132085952").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOutputField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("solly.tutorials.calculator", "OutputField", 0xb82c1489ef4142a8L, 0xa822be676a783f97L, 0x6edbdfc7873c259dL);
    b.class_(false, false, false);
    b.origin("r:541fa709-e489-498e-8c7b-45b0d1ff3578(solly.tutorials.calculator.structure)/7988224412132058525");
    b.aggregate("expression", 0x6edbdfc7873c4223L).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL).optional(false).ordered(true).multiple(false).origin("7988224412132065827").done();
    return b.create();
  }
}
