package DisFunctional.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Program = 0;
  public static final int RoutineCall = 1;
  public static final int RoutineDeclaration = 2;
  public static final int Statement = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xf6ffa208e9974a9eL, 0x80959550ead5b5afL);
    builder.put(0x6edbdfc7874c8f1cL, Program);
    builder.put(0x6edbdfc7874c9411L, RoutineCall);
    builder.put(0x6edbdfc7874c9bdfL, RoutineDeclaration);
    builder.put(0x6edbdfc7874c8f22L, Statement);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
