package DisFunctional.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptProgram = createDescriptorForProgram();
  /*package*/ final ConceptDescriptor myConceptRoutineCall = createDescriptorForRoutineCall();
  /*package*/ final ConceptDescriptor myConceptRoutineDeclaration = createDescriptorForRoutineDeclaration();
  /*package*/ final ConceptDescriptor myConceptStatement = createDescriptorForStatement();
  private final LanguageConceptSwitch myConceptIndex;

  public StructureAspectDescriptor() {
    myConceptIndex = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptProgram, myConceptRoutineCall, myConceptRoutineDeclaration, myConceptStatement);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myConceptIndex.index(id)) {
      case LanguageConceptSwitch.Program:
        return myConceptProgram;
      case LanguageConceptSwitch.RoutineCall:
        return myConceptRoutineCall;
      case LanguageConceptSwitch.RoutineDeclaration:
        return myConceptRoutineDeclaration;
      case LanguageConceptSwitch.Statement:
        return myConceptStatement;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myConceptIndex.index(c);
  }

  private static ConceptDescriptor createDescriptorForProgram() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DisFunctional", "Program", 0xf6ffa208e9974a9eL, 0x80959550ead5b5afL, 0x6edbdfc7874c8f1cL);
    b.class_(false, false, true);
    b.origin("r:6760b883-d39e-498a-9d76-7cf99c529a82(DisFunctional.structure)/7988224412133134108");
    b.aggregate("statements", 0x6edbdfc7874c8f2fL).target(0xf6ffa208e9974a9eL, 0x80959550ead5b5afL, 0x6edbdfc7874c8f22L).optional(true).ordered(true).multiple(true).origin("7988224412133134127").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRoutineCall() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DisFunctional", "RoutineCall", 0xf6ffa208e9974a9eL, 0x80959550ead5b5afL, 0x6edbdfc7874c9411L);
    b.class_(false, false, false);
    b.super_("DisFunctional.structure.Statement", 0xf6ffa208e9974a9eL, 0x80959550ead5b5afL, 0x6edbdfc7874c8f22L);
    b.origin("r:6760b883-d39e-498a-9d76-7cf99c529a82(DisFunctional.structure)/7988224412133135377");
    b.associate("routine", 0x6edbdfc7874c9fa5L).target(0xf6ffa208e9974a9eL, 0x80959550ead5b5afL, 0x6edbdfc7874c9bdfL).optional(true).origin("7988224412133138341").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRoutineDeclaration() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DisFunctional", "RoutineDeclaration", 0xf6ffa208e9974a9eL, 0x80959550ead5b5afL, 0x6edbdfc7874c9bdfL);
    b.class_(false, false, false);
    b.super_("DisFunctional.structure.Statement", 0xf6ffa208e9974a9eL, 0x80959550ead5b5afL, 0x6edbdfc7874c8f22L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6760b883-d39e-498a-9d76-7cf99c529a82(DisFunctional.structure)/7988224412133137375");
    b.aggregate("program", 0x6edbdfc7874d3107L).target(0xf6ffa208e9974a9eL, 0x80959550ead5b5afL, 0x6edbdfc7874c8f1cL).optional(false).ordered(true).multiple(false).origin("7988224412133175559").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStatement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DisFunctional", "Statement", 0xf6ffa208e9974a9eL, 0x80959550ead5b5afL, 0x6edbdfc7874c8f22L);
    b.class_(false, false, false);
    b.origin("r:6760b883-d39e-498a-9d76-7cf99c529a82(DisFunctional.structure)/7988224412133134114");
    return b.create();
  }
}
