package solly.tutorials.calculator.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import javax.swing.JTextField;
import java.awt.GridLayout;
import javax.swing.SwingUtilities;

public class test_2 extends JFrame {
  private DocumentListener listener = new DocumentListener() {
    public void insertUpdate(DocumentEvent p0) {
      update();
    }
    public void removeUpdate(DocumentEvent p0) {
      update();
    }
    public void changedUpdate(DocumentEvent p0) {
      update();
    }
  };

  private JTextField outputField_a_0 = new JTextField();
  public test_2() {
    setTitle("test_2");
    setLayout(new GridLayout(0, 2));
    update();
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    pack();
    setVisible(true);
  }
  public void update() {
    try {
    } catch (NumberFormatException e) {
    }
    outputField_a_0.setText("" + (1));
  }
  public static void main(String[] args) {
    SwingUtilities.invokeLater(new Runnable() {
      public void run() {
        new test_2();
      }
    });
  }
}
