package solly.tutorials.calculator.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.scope.EmptyScope;
import jetbrains.mps.smodel.SNodePointer;

public class InputFieldReference_Constraints extends BaseConstraintsDescriptor {
  public InputFieldReference_Constraints() {
    super(MetaAdapterFactory.getConcept(0xb82c1489ef4142a8L, 0xa822be676a783f97L, 0x6edbdfc7873c90bfL, "solly.tutorials.calculator.structure.InputFieldReference"));
  }

  @Override
  protected Map<SReferenceLink, ReferenceConstraintsDescriptor> getSpecifiedReferences() {
    Map<SReferenceLink, ReferenceConstraintsDescriptor> references = new HashMap<SReferenceLink, ReferenceConstraintsDescriptor>();
    references.put(MetaAdapterFactory.getReferenceLink(0xb82c1489ef4142a8L, 0xa822be676a783f97L, 0x6edbdfc7873c90bfL, 0x6edbdfc7873c90c0L, "field"), new BaseReferenceConstraintsDescriptor(MetaIdFactory.refId(0xb82c1489ef4142a8L, 0xa822be676a783f97L, 0x6edbdfc7873c90bfL, 0x6edbdfc7873c90c0L), this) {
      @Override
      public boolean hasOwnScopeProvider() {
        return true;
      }
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return breakingNode_43tbk9_a0a0a0a0a1a0b0a1a2;
          }
          @Override
          public Scope createScope(final IOperationContext operationContext, final ReferenceConstraintsContext _context) {
            {
              Scope scope = Scope.getScope(_context.getContextNode(), _context.getContainmentLink(), _context.getPosition(), MetaAdapterFactory.getConcept(0xb82c1489ef4142a8L, 0xa822be676a783f97L, 0x6edbdfc7873bfb78L, "solly.tutorials.calculator.structure.InputField"));
              return (scope == null ? new EmptyScope() : scope);
            }
          }
        };
      }
    });
    return references;
  }
  private static SNodePointer breakingNode_43tbk9_a0a0a0a0a1a0b0a1a2 = new SNodePointer("r:bf65cd28-3126-4b03-9c84-542df0928d5e(solly.tutorials.calculator.constraints)", "7988224412133102098");
}
