package DisFunctional.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt_a0a = ((SAbstractConcept) concept);
    switch (index_xbvbvu_a0a.index(cncpt_a0a)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Program_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new RoutineCall_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new RoutineDeclaration_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex index_xbvbvu_a0a = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xf6ffa208e9974a9eL, 0x80959550ead5b5afL, 0x6edbdfc7874c8f1cL), MetaIdFactory.conceptId(0xf6ffa208e9974a9eL, 0x80959550ead5b5afL, 0x6edbdfc7874c9411L), MetaIdFactory.conceptId(0xf6ffa208e9974a9eL, 0x80959550ead5b5afL, 0x6edbdfc7874c9bdfL)).seal();
}
